pipelines:
  pname-1:
    group: pgroup
    materials:
      test-scripts:
        git: https://github.com/dudadornelles/gocd-reproduce-bug.git
    
    stages:
      - build: 
          clean_workspace: true
          jobs:
            build-app: 
              resources:
                - abc
              tasks:
                - exec: 
                    command: echo
                    arguments:
                      - HI
